export {default as Home} from './Home'
export {default as About} from './About'
export {default as Login} from './Login'
export {default as Signup} from './Signup'
export {default as PasswordReset} from './PasswordReset'
export {default as Dashboard} from './Dashboard/Dashboard'